baseURL = 'https://udaydahiya.org'
theme = "hugo-apero"
languageCode = "en-us"
title = "Uday | Portfolio"
author = "Uday"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
copyright = ""
metaDataFormat = "yaml"
footnoteReturnLinkContents = "&#8617;"

[pagination]
  pagerSize = 10

preserveTaxonomyNames = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
enableEmoji = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
    hardwraps = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
  [markup.highlight]
    style = "github"

[params]
  orgName = ""
  orgLocal = ""
  description = "AI Engineer exploring applied AI, automation & systems thinking."
  favicon = "/img/favicon.ico"
  logo = ""
  mainSections = ["project", "post", "reads"]
  navallcaps = true
  socialInHeader = false
  socialInFooter = true
  sharing_image = "/img/papillons.jpg"
  twitter = ""

  # use a built-in color theme
  # one of: earth / forest / grayscale / magma / paper / peach / plum /
  # poppy / sky / water / coffee
  theme = "paper"

  textFontFamily = "'Inter', system-ui, -apple-system, sans-serif"
  headingFontFamily = "'Space Grotesk', system-ui, -apple-system, sans-serif"

  # Custom theme styling
  custom_theme = "portfolio"
  customtextFontFamily = "Inter"
  customheadingFontFamily = "Space Grotesk"

[[params.social]]
    icon = "github"
    icon_pack = "fab"
    url = "https://github.com/Uday-461"
[[params.social]]
    icon = "linkedin"
    icon_pack = "fab"
    url = ""

# Configure header menu for centered navigation
[[menu.header]]
  name = "Home"
  title = "Home"
  url = "/"
  weight = 1
[[menu.header]]
  name = "Projects"
  title = "Projects"
  url = "/project/"
  weight = 2
[[menu.header]]
  name = "Reads"
  title = "Reads"
  url = "/reads/"
  weight = 3
[[menu.header]]
  name = "Blog"
  title = "Blog"
  url = "/post/"
  weight = 4

# Configure footer menu if needed
[[menu.footer]]
  name = "GitHub"
  title = "GitHub"
  url = "https://github.com/Uday-461"
  weight = 1

# Taxonomies for organizing content
[taxonomies]
  tag = "tags"
  category = "categories"

# Site outputs
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]